var menu = [
			{ "id": "1", "parentId": "", "text": "审定监察子系统PR", "url": "" },
            { "id": "3", "parentId": "", "text": "审定监察子系统", "url": "" },
            { "id": "5", "parentId": "", "text": "电子规章子系统", "url": "" },
            { "id": "6", "parentId": "", "text": "基础信息子系统", "url": "" },
            { "id": "4", "parentId": "", "text": "129外航审定检查系统", "url": "" },
            { "id": "2", "parentId": "", "text": "航空器评审", "url": "" },
			

            //使用困难报告系统
            { "id": "71", "parentId": "7", "text": "首页", "url": "../demo/easyui/grid" },
            { "id": "72", "parentId": "7", "text": "使用困难", "url": "" },
            { "id": "73", "parentId": "7", "text": "使用月报", "url": "" },
            { "id": "74", "parentId": "7", "text": "变化信息", "url": "" },
            { "id": "75", "parentId": "7", "text": "厂家故障报告", "url": "" },
            { "id": "76", "parentId": "7", "text": "机载设备备注信息", "url": "" },
            { "id": "77", "parentId": "7", "text": "信息处理", "url": "" },
            { "id": "78", "parentId": "7", "text": "查询统计", "url": "" },
            { "id": "79", "parentId": "7", "text": "多维分析", "url": "" },
            { "id": "7a", "parentId": "7", "text": "风险评估", "url": "" },
            { "id": "7b", "parentId": "7", "text": "基础信息", "url": "" },

            { "id": "721", "parentId": "72", "text": "初始报告", "url": "" },
            { "id": "722", "parentId": "72", "text": "调查报告", "url": "" },
            { "id": "723", "parentId": "72", "text": "通航使用困难报告", "url": "" },
            { "id": "724", "parentId": "72", "text": "自愿报告", "url": "" },
			{ "id": "725", "parentId": "72", "text": "重要问题处理单", "url": "" },
			{ "id": "726", "parentId": "72", "text": "移交单", "url": "" },
			{ "id": "727", "parentId": "72", "text": "使用困难报告管理", "url": "" },
			
			{ "id": "7211", "parentId": "721", "text": "近期使用困难报告", "url": "../demo/easyui/grid" },
			{ "id": "7212", "parentId": "721", "text": "初始报告查询", "url": "http://fontawesome.io/icons/" },
			{ "id": "7221", "parentId": "722", "text": "调查报告签署", "url": "" },
			{ "id": "7222", "parentId": "722", "text": "调查报告查询", "url": "" },
			{ "id": "7223", "parentId": "722", "text": "调查报告附件检索", "url": "" },
			{ "id": "7231", "parentId": "723", "text": "使用困难报告签署", "url": "" },
			{ "id": "7232", "parentId": "723", "text": "使用困难报告查询", "url": "" },
			{ "id": "7233", "parentId": "723", "text": "使用困难报告管理", "url": "" },
			{ "id": "7241", "parentId": "724", "text": "自愿报告处理", "url": "" },
			{ "id": "7251", "parentId": "725", "text": "重要问题处理单", "url": "" },
			{ "id": "7252", "parentId": "725", "text": "重要问题处理单查询", "url": "" },
			{ "id": "7261", "parentId": "726", "text": "移交单", "url": "" },
			{ "id": "7262", "parentId": "726", "text": "移交单查询", "url": "" },
			{ "id": "7271", "parentId": "727", "text": "初始报告管理", "url": "" },
			{ "id": "7272", "parentId": "727", "text": "调查报告管理", "url": "" },
			
			{ "id": "731", "parentId": "73", "text": "航空器月报", "url": "" },
			{ "id": "732", "parentId": "73", "text": "发动机月报", "url": "" },
			
			{ "id": "7311", "parentId": "731", "text": "航空器月报检查", "url": "http://news.qq.com" },
			{ "id": "7312", "parentId": "731", "text": "航空器月报查询", "url": "" },
			{ "id": "7313", "parentId": "731", "text": "航空器月报管理", "url": "" },
			{ "id": "7314", "parentId": "731", "text": "航空器月报管理日志", "url": "" },
			{ "id": "7321", "parentId": "732", "text": "发动机月报检查", "url": "" },
			{ "id": "7322", "parentId": "732", "text": "发动机月报查询", "url": "" },
			{ "id": "7323", "parentId": "732", "text": "发动机月报管理", "url": "" },
			{ "id": "7324", "parentId": "732", "text": "发动机月报管理日志", "url": "" },
			


            //审定监察子系统PR
            { "id": "11", "parentId": "1", "text": "持续监察", "url": "" },
            { "id": "12", "parentId": "1", "text": "合格审定", "url": "" },
            { "id": "11a", "parentId": "11", "text": "首页", "url": "" },
            { "id": "11b", "parentId": "11", "text": "系统构型", "url": "http://www.csdn.net" },
            { "id": "11c", "parentId": "11", "text": "计划管理", "url": "http://www.douban.com" },
            { "id": "11d", "parentId": "11", "text": "资源管理", "url": "http://www.baidu.com" },
            { "id": "11e", "parentId": "11d", "text": "数据收集", "url": "" },
            { "id": "11f", "parentId": "11d", "text": "分析评估", "url": "" },
            { "id": "11g", "parentId": "11d", "text": "绩效分析", "url": "" },
            { "id": "11h", "parentId": "11d", "text": "检查单下载", "url": "" },
            { "id": "11i", "parentId": "11d", "text": "配置PI", "url": "" },
            { "id": "11j", "parentId": "11d", "text": "角色管理", "url": "" },
            { "id": "11k", "parentId": "11d", "text": "专项检查", "url": "" },
            { "id": "11l", "parentId": "11d", "text": "系统实时监控", "url": "" },
            { "id": "11m", "parentId": "11a", "text": "本辖区公司配置", "url": "../oeas/demo.html" },
            { "id": "11n", "parentId": "11a", "text": "查看辖区公司配置", "url": "http://www.infoq.com/" },
            { "id": "11l", "parentId": "11a", "text": "系统实时监控", "url": "" },
            { "id": "11m", "parentId": "11b", "text": "本辖区公司配置", "url": "" },
            { "id": "11n", "parentId": "11b", "text": "查看辖区公司配置", "url": "" },
            { "id": "11l", "parentId": "11b", "text": "系统实时监控", "url": "" },
            { "id": "11m", "parentId": "11c", "text": "本辖区公司配置", "url": "" },
            { "id": "11n", "parentId": "11c", "text": "查看辖区公司配置", "url": "" },
            { "id": "11l", "parentId": "11c", "text": "系统实时监控", "url": "" },
            { "id": "11m", "parentId": "11c", "text": "本辖区公司配置", "url": "" },
            { "id": "11n", "parentId": "11c", "text": "查看辖区公司配置", "url": "" },



            { "id": "12a", "parentId": "12", "text": "审定工作单管理", "url": "http://news.qq.com" },
            { "id": "12b", "parentId": "12", "text": "合格审定", "url": "http://www.cnblogs.com/" },
            { "id": "12c", "parentId": "12", "text": "符合性声明检查", "url": "" },
            { "id": "12d", "parentId": "12", "text": "SAI检查", "url": "" },
            { "id": "21", "parentId": "2", "text": "首页", "url": "" },
            { "id": "22", "parentId": "2", "text": "工作桌面", "url": "" },
            { "id": "23", "parentId": "2", "text": "项目管理", "url": "" },
            { "id": "24", "parentId": "2", "text": "文档函件库", "url": "" },
            { "id": "25", "parentId": "2", "text": "使用问题报告", "url": "" },
            { "id": "26", "parentId": "2", "text": "统计分析", "url": "" },
            { "id": "31", "parentId": "3", "text": "运行规范查看", "url": "" },
            { "id": "32", "parentId": "3", "text": "统计分析", "url": "" },
            { "id": "33", "parentId": "3", "text": "合格证持有人", "url": "" },
            { "id": "34", "parentId": "3", "text": "模板管理", "url": "" },
            { "id": "35", "parentId": "3", "text": "基础数据管理", "url": "" },
            { "id": "31a", "parentId": "31", "text": "121部运营人", "url": "" },
            { "id": "31b", "parentId": "31", "text": "135部运营人", "url": "" },
            { "id": "31c", "parentId": "31", "text": "129部运营人", "url": "" },
            { "id": "31d", "parentId": "31", "text": "未运行运营人", "url": "" },
            { "id": "32a", "parentId": "32", "text": "基本信息", "url": "" },
            { "id": "32b", "parentId": "32", "text": "管理人员", "url": "" },
            { "id": "32c", "parentId": "32", "text": "机队查询", "url": "" },
            { "id": "32d", "parentId": "32", "text": "航空器查询", "url": "" },
            { "id": "32e", "parentId": "32", "text": "批准机场", "url": "" },
            { "id": "32f", "parentId": "32", "text": "航路运行区域", "url": "" },
            { "id": "41", "parentId": "4", "text": "首页", "url": "" },
            { "id": "42", "parentId": "4", "text": "查看运行规范", "url": "" },
            { "id": "43", "parentId": "4", "text": "计划管理", "url": "" },
            { "id": "44", "parentId": "4", "text": "资源管理", "url": "" },
            { "id": "45", "parentId": "4", "text": "数据收集", "url": "" },
            { "id": "46", "parentId": "4", "text": "分析评估", "url": "" },
            { "id": "47", "parentId": "4", "text": "运行评估", "url": "" },
            { "id": "48", "parentId": "4", "text": "系统实时监控", "url": "" },
            { "id": "49", "parentId": "4", "text": "绩效分析", "url": "" },
            { "id": "410", "parentId": "4", "text": "辖区监管航空公司构型", "url": "" },
            { "id": "411", "parentId": "4", "text": "资料共享", "url": "" },
            { "id": "412", "parentId": "4", "text": "代码共享安全审计", "url": "" },
            { "id": "48a", "parentId": "48", "text": "监察工作绩效", "url": "" },
            { "id": "48b", "parentId": "48", "text": "检查员工作量", "url": "" },
            { "id": "48c", "parentId": "48", "text": "检查任务完成明细", "url": "" },
            { "id": "48d", "parentId": "48", "text": "日常监察动态", "url": "" },
            { "id": "48e", "parentId": "48", "text": "监察计划编制情况", "url": "" },
            { "id": "48f", "parentId": "48", "text": "监察计划执行情况", "url": "" },
            { "id": "48g", "parentId": "48", "text": "年度监察任务汇总", "url": "" },
            { "id": "48h", "parentId": "48", "text": "合格审定工作量", "url": "" },
            { "id": "48i", "parentId": "48", "text": "新成立公司统计", "url": "" },
            { "id": "48j", "parentId": "48", "text": "航空器变化情况", "url": "" },
            { "id": "48k", "parentId": "48", "text": "航线变化情况", "url": "" },
            { "id": "410a", "parentId": "410", "text": "停机坪检查构型", "url": "" },
            { "id": "410b", "parentId": "410", "text": "航站检查构型", "url": "" },
            { "id": "410c", "parentId": "410", "text": "主运营基地检查构型", "url": "" },
            { "id": "410d", "parentId": "410", "text": "汇总", "url": "" },
            { "id": "411a", "parentId": "411", "text": "目录导航", "url": "" },
            { "id": "411b", "parentId": "411", "text": "文件检索", "url": "" },
            { "id": "411c", "parentId": "411", "text": "近期发布", "url": "" },
            { "id": "51", "parentId": "5", "text": "规章检索", "url": "" },
            { "id": "52", "parentId": "5", "text": "我的规章", "url": "" },
            { "id": "53", "parentId": "5", "text": "规章阅读", "url": "" },
            { "id": "51a", "parentId": "51", "text": "条款检索", "url": "" },
            { "id": "51b", "parentId": "51", "text": "规章检索", "url": "" },
            { "id": "52a", "parentId": "52", "text": "我的收藏", "url": "" },
            { "id": "52b", "parentId": "52", "text": "在线交流", "url": "" },
            { "id": "52c", "parentId": "52", "text": "回复管理", "url": "" },
            { "id": "52d", "parentId": "52", "text": "术语管理", "url": "" },
            { "id": "52e", "parentId": "52", "text": "释义管理", "url": "" },
            { "id": "52f", "parentId": "52", "text": "案例共享", "url": "" },
            { "id": "53a", "parentId": "53", "text": "目录", "url": "" },
            { "id": "53b", "parentId": "53", "text": "书签", "url": "" },
            { "id": "53c", "parentId": "53", "text": "收藏", "url": "" },
            { "id": "61", "parentId": "6", "text": "机场基础信息", "url": "" },
            { "id": "62", "parentId": "6", "text": "生产厂家信息", "url": "" },
            { "id": "63", "parentId": "6", "text": "机型信息", "url": "" },

            //基础信息
            { "id": "61a", "parentId": "61", "text": "华北地区管理局", "url": "" },
            { "id": "61b", "parentId": "61", "text": "东北地区管理局", "url": "" },
            { "id": "61c", "parentId": "61", "text": "华东地区管理局", "url": "" },
            { "id": "61d", "parentId": "61", "text": "中南地区管理局", "url": "" },
            { "id": "61f", "parentId": "61", "text": "西南地区管理局", "url": "" },
            { "id": "61g", "parentId": "61", "text": "西北地区管理局", "url": "" },
            { "id": "61h", "parentId": "61", "text": "新疆管理局", "url": "" }
];